version: '2'
services:
  vnstartupdir-postgresql:
    image: postgres:11.4
    # volumes:
    #     - ~/volumes/jhipster/vnstartupdir/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=vnstartupdir
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
